describe('Calendar', function() {
  describe('My Availability', function() {
    before(function() {
      cy.server()

      cy.fixture('purview_users').as('purviewUsers')
      cy.fixture('purview_availabilities').as('purviewAvailabilities')
      cy.fixture('availabilities').as('availabilities')

      cy.route(/.*\/purview_users.*/, '@purviewUsers').as('purviewUsersRoute')
      cy.route(/.*\/purview_availabilities.*/, '@purviewAvailabilities').as('purviewAvailabilitiesRoute')
      cy.route(/.*\/availabilities.*/, '@availabilities').as('availabilitiesRoute')

      cy.visit('/components/calendar')

      cy.wait(['@purviewUsersRoute', '@purviewAvailabilitiesRoute', '@availabilitiesRoute'])
    })
    it('loads the component', function() {
      cy.get('h2').should('have.text', 'Calendar')
    })
    describe('grid', function() {
      it('shows the hour grid', function() {
        cy.get('.is-today').as('today').find('.sim-timelines').should('not.exist')
        cy.get('@today').find('.sim-calendar--grid--tools svg').click({force: true})
        cy.get('@today').find('.sim-timelines').should('exist')
      })
      it('adds a block from 6am to 7am', function() {
        cy.get('.sim-calendar--grid').as('grid').find('.sim-timeblock').should('not.exist')
        cy.get('@grid').find('.is-hour-6').click()
        cy.get('@grid').find('.sim-timeblock').as('timeblock').should('exist')
        cy.get('@timeblock').find('.sim-timeblock--info--hours').contains('1 hour')
      })
      it('expands the block from 1 hour to 4 hours by adjusting the end time', function() {
        cy.get('.sim-calendar--grid').as('grid')
          .find('.sim-timeblock--info--hours').as('hours').contains('1 hour')
        cy.get('@grid').find('.sim-timeblock > .sim-timeblock--handle--down')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 45})
          .trigger('mouseup')
        cy.get('@hours').contains('4 hours')
      })
      it('contracts the block from 4 hours to 2 hours by adjusting the end time', function() {
        cy.get('.sim-calendar--grid').as('grid')
          .find('.sim-timeblock--info--hours').as('hours').contains('4 hours')
        cy.get('@grid').find('.sim-timeblock > .sim-timeblock--handle--down')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: -10})
          .trigger('mouseup')
        cy.get('@hours').contains('2 hours')
      })
      it('moves a block from a 6am start to a 1pm start', function() {
        cy.get('.sim-calendar--grid').as('grid').find('.sim-timeblock').should('have.attr', 'style', '--start:6; --duration:2;')
        cy.get('@grid').find('.sim-timeblock--mover')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 105})
          .trigger('mouseup')
        cy.get('@grid').find('.sim-timeblock--info--hours').contains('2 hours')
        cy.get('.sim-calendar--grid').find('.sim-timeblock').should('have.attr', 'style', '--start:13; --duration:2;')
      })
      it('expands the block from 2 hours to 4 hours by adjusting the start time', function() {
        cy.get('.sim-calendar--grid').as('grid')
          .find('.sim-timeblock--info--hours').as('hours').contains('2 hours')
        cy.get('@grid').find('.sim-timeblock > .sim-timeblock--handle--up')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 25})
          .trigger('mouseup')
        cy.get('@hours').contains('4 hours')
      })
      it('contracts the block from 4 hours to 2 hours by adjusting the start time', function() {
        cy.get('.sim-calendar--grid').as('grid')
          .find('.sim-timeblock--info--hours').as('hours').contains('4 hours')
        cy.get('@grid').find('.sim-timeblock > .sim-timeblock--handle--up')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 50})
          .trigger('mouseup')
        cy.get('@hours').contains('2 hours')
      })
      it('removes a block through the handle', function() {
        cy.get('.sim-calendar--grid').as('grid').find('.sim-timeblock').as('timeblock').should('exist')
        cy.get('@timeblock').find('.sim-timeblock--remover').click()
        cy.get('@grid').find('sim-timeblock').should('not.exist')
      })
      it('collapses the view', function() {
        cy.get('.is-today').as('today').find('.sim-timelines').should('exist')
        cy.get('@today').find('.sim-calendar--grid--tools svg').click({force: true})
        cy.get('@today').find('.sime-timelines').should('not.exist')
      })
    })
    describe('day-control panel', function() {
      it('adds a block from 6am to 7am', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel').find('.sim-timeblock').should('not.exist')
        cy.get('@day-control-panel').find('.is-hour-6').click()
        cy.get('@day-control-panel').find('.sim-timeblock').as('timeblock').should('exist')
        cy.get('@day-control-panel').find('.sim-timeblock--info--hours').contains('1 hour')
      })
      it('expands the block from 1 hour to 4 by adjusting the end time', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel')
          .find('.sim-timeblock--info--hours').as('hours').contains('1 hour')
        cy.get('@day-control-panel').as('day-control-panel').find('.sim-timeblock > .sim-timeblock--handle--down')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 75})
          .trigger('mouseup')
        cy.get('@hours').contains('4 hours')
      })
      it('contracts the block from 4 hours to 2 by adjusting the end time', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel')
          .find('.sim-timeblock--info--hours').as('hours').contains('4 hours')
        cy.get('@day-control-panel').find('.sim-timeblock > .sim-timeblock--handle--down')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 40})
          .trigger('mouseup')
        cy.get('@hours').contains('2 hours')
      })
      it('moves a block from a 6am start to a 1pm start', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel').find('.sim-timeblock').should('have.attr', 'style', '--start:6; --duration:2;')
        cy.get('@day-control-panel').find('.sim-timeblock--mover')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 135})
          .trigger('mouseup')
        cy.get('@day-control-panel').find('.sim-timeblock--info--hours').contains('2 hours')
        cy.get('@day-control-panel').find('.sim-timeblock').should('have.attr', 'style', '--start:13; --duration:2;')
      })
      it('expands the block from 2 hours to 4 by adjusting the start time', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel')
          .find('.sim-timeblock--info--hours').as('hours').contains('2 hours')
        cy.get('@day-control-panel').find('.sim-timeblock > .sim-timeblock--handle--up')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 85})
          .trigger('mouseup', {force: true})
        cy.get('@hours').contains('4 hours')
      })
      it('contracts the block from 4 hours to 2 by adjusting the start time', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel')
          .find('.sim-timeblock--info--hours').as('hours').contains('4 hours')
        cy.get('@day-control-panel').find('.sim-timeblock > .sim-timeblock--handle--up')
          .trigger('mousedown', {which: 1})
          .trigger('mousemove', {clientY: 115})
          .trigger('mouseup')
        cy.get('@hours').contains('2 hours')
      })
      it('removes a block through the handle', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel').find('.sim-timeblock').as('timeblock').should('exist')
        cy.get('@timeblock').find('.sim-timeblock--remover').click()
        cy.get('@day-control-panel').find('sim-timeblock').should('not.exist')
      })
      it('removes a block through the top nav', function() {
        cy.get('.sim-calendar--day-control-panel').as('day-control-panel').find('.sim-timeblock').should('not.exist')
        cy.get('@day-control-panel').find('.is-hour-6').click()
        cy.get('@day-control-panel').find('.sim-timeblock').should('exist')
        cy.get('@day-control-panel').find('.sim-timepicker--display-date').as('display-date').contains('1 hour')
        cy.get('@display-date').find('.sim-timepicker--remove-blocks').click()
        cy.get('@day-control-panel').find('sim-timeblock').should('not.exist')
      })
    })
    // We need inject the current day as a dependency for this to be testable
    xdescribe('navigation', function() {
      describe('month', function() {
        it('backward')
        it('forward')
      })
      describe('day', function() {
        it('backward')
        it('forward')
        it('today')
      })
      describe('control panel', function() {
        it('backward')
        it('forward')
      })
    })
  })
})
